site_name: "pyfxp"
site_description: "Python fixed-point library."
site_url: https://pyfxp.readthedocs.io/en
repo_url: https://github.com/ericsmacedo/pyfxp
copyright: Copyright (c) 2025 ericsmacedo

theme:
  name: material
  palette:
    - media: "(prefes-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefes-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select
    - content.code.annotate

nav:
  - Home:
      - Welcome to pyfxp: index.md
      - Examples:
          - fixed-point integrator: examples/example_int.md
      - Contributing: contributing.md
  - API:
      - fixed-point functions:
        - fxp: api/fxp.md
        - fpxt: api/fxpt.md
        - Q: api/Q.md
        - FxpSpec: api/FxpSpec.md
      - Constants: api/constants.md

plugins:
  - search
  - include-markdown
  - autorefs
  - literate-nav:
      nav_file: README.md
      implicit_index: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # Tables are generally too large, lists will fix this.
            docstring_section_style: table
            show_root_heading: true
            parameter_headings: false
            # Show the type of symbol (class, function, etc.) in the table of contents.
            show_symbol_type_toc: true
            # Render headings for type parameters too.
            # type_parameter_headings: true
            line_length: 88
            docstring_options:
              ignore_init_summary: true
            summary: true
            show_source: false
            unwrap_annotated: true
            members_order: source
            show_docstring_parameters: true
            show_docstring_other_parameters: true
            separate_signature: true
            signature_crossrefs: true
            show_signature: true
            show_signature_annotations: false
            show_symbol_type_heading: true
            # preload_modules: [pydantic]
            inherited_members: false
            docstring_style: numpy
          inventories:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - admonition
  - attr_list
  - mkdocs-click
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

watch:
  - src
  - docs
  - CONTRIBUTING.md
